
# Smelted
# Gets the smelted version of an item.
expression:
    patterns:
        (smelt|cook)[ed] %itemtype%
        %itemtype% (smelt|cook)ed
    get:
        loop all recipes:
            recipe type of recipe loop-value is furnace_recipe
            ingredients of recipe loop-value contains 1 of expr-1
            set {_result} to result of recipe loop-value
            set item amount of {_result} to item amount of expr-1
            return {_result}
        return expr-1
