
# /list
slash command list:
    description: List all online players
    bot: ChatLink
    trigger:
        set {_p::*} to (all players)
        set {_size} to (size of {_p::*})
        set {_s} to ("" if {_size} is 1 else "s")
        set {_response} to "**%{_size}%** player%{_s}% online: "
        loop {_p::*}:
            add (name of loop-value) to {_response}
            if {-playerdata::%loop-value%::lastmoved} < (now - 5 minutes):
                add " (AFK)" to {_response}
            loop-iteration isn't (size of {_p::*})
            add ", " to {_response}
        reply with hidden {_response}

# /exec
slash command exec <string="command">:
    description: Remotely run effect commands
    bot: ChatLink
    arguments:
        code: Command to execute
    trigger:
        # permission
        if {-env::discordExecIds::*} contains (discord id of event-user):
            set {_command} to argument "command" as string
            log info "Executing command from discord: §3%{_command}%"
            if parse effect {_command} = true:
                reply with hidden ":white_check_mark: Successfully executed `%{_command}%`"
            else:
                reply with hidden ":warning: Failed to execute `%{_command}%`"
        else:
            reply with hidden "You don't have permission to do this."
            exit trigger
