
when ready to load recipes:
    register furnace recipe:
        id: "turtle:chorium_ingot"
        result: getItem("turtle:chorium_ingot")
        input: getItem("turtle:chorium_cluster")
        experience: 10.0
        category: "misc"
    register blasting recipe:
        id: "turtle:chorium_ingot_blasting"
        result: getItem("turtle:chorium_ingot")
        input: getItem("turtle:chorium_cluster")
        experience: 10.0
        category: "misc"
