
import:
    io.papermc.paper.event.block.VaultChangeStateEvent
on VaultChangeStateEvent:
    clearRewardedPlayers(blockstate of event.getBlock())

local function clearRewardedPlayers(b:blockstate):
    loop ...{_b}.getRewardedPlayers():
        {_b}.removeRewardedPlayer(loop-value)
    update {_b}

# for already used vaults
on player interact:
    event-block is vault
    clearRewardedPlayers(blockstate of event-block)
