
import:
    org.bukkit.entity.TNTPrimed
    org.bukkit.entity.minecart.ExplosiveMinecart

on right click:
    getId(player's tool) is "minecraft:shears"
    if all:
        event-entity isn't instance of TNTPrimed
        event-entity isn't instance of ExplosiveMinecart
    then:
        exit trigger
    if event-entity is instance of TNTPrimed:
        set {_loc} to (event-entity's location ~ vector(0.5,0.75,0.5))
        drop 1 of tnt at {_loc}
    else if event-entity is instance of ExplosiveMinecart:
        set {_loc} to (event-entity's location ~ vector(0.5,0.5,0.5))
        drop 1 of (material from key "tnt_minecart") at {_loc}
    play sound "minecraft:entity.mooshroom.shear" with volume 0.5 at {_loc}
    kill event-entity
    player's gamemode isn't creative
    player.damageItemStack(hand_slot, 1)
