
# Villager work station
# Gets the location of a villager's workstation.
expression:
    patterns:
        [potential:(potential|wanted)] (work|job)[ ](station|site) of %entity%
        %entity%'s [potential:(potential|wanted)] (work|job)[ ](station|site)
    get:
        if (parse tags contains "potential"):
            return block at (potential_job_site memory of expr-1)
        else:
            return block at (job_site memory of expr-1)
