
brig command /turtle:catfact:
    trigger:
        async run 0 ticks later:
            set {_json} to (first element of urlfetch "https://catfact.ninja/fact")
            set {_catfact} to valueFromJson({_json}, "fact")
            if {_catfact} ends with ".":
                set {_catfact} to (subtext of {_catfact} from character 1 to ((length of {_catfact})-1))
            send " &d🐈 Cat Fact: &f%{_catfact}% :3"
