
# item > id
function getId(item:item) :: string:
    set {_id} to (string tag "customId" of (custom nbt of {_item}))
    return {_id} if {_id} is set else (raw name of {_item})

# id > item
function getItem(id:string) :: item:
    set {_id} to namespaced key from {_id}
    if {-customItems::%{_id}%} is set:
        return {-customItems::%{_id}%}
    else if (itemtype from key {_id}) is set:
        return itemtype from key {_id}
