
# cactus can't destroy items
on damage of dropped item:
    damage cause is contact, block explosion, or entity explosion
    cancel event

# explosions launch items
on damage of dropped item:
    damage cause is block explosion or entity explosion
    cancel event
    set {_loc} to damage location of damage source
    set {_v} to vector from {_loc} to victim
    set vector length of {_v} to max(0, 4-vector length of {_v})
    push victim {_v}
