
on load:
    set {-features::elytrabounce::name} to "Elytra bouncing"
    set {-features::elytrabounce::desc} to "Hold space to not stop gliding"
    set {-features::elytrabounce::icon} to elytra

# Elytra bouncing!
on toggle gliding:
    {enabledFeatures::elytrabounce} is true
    player is gliding
    player is on ground
    player is pressing jump key
    player isn't sneaking
    cancel event
    # make sure cloud jump is reset
    set {-playerdata::%player%::canCloudJump} to true
